### ISSUE TITLE
NBTException when opening .mca file from 1.14 snapshot

### ISSUE THREAD

**Issue by kasamikona** [jaquadro/NBTExplorer#72]
NBTExplorer encountered the following exception while trying to run: Exception
Message: Exception of type 'System.Exception' was thrown.

-------
   at Substrate.Nbt.NbtTree.ReadValue(TagType type)
   at Substrate.Nbt.NbtTree.ReadTag(TagNodeCompound parent)
   at Substrate.Nbt.NbtTree.ReadCompound()
   at Substrate.Nbt.NbtTree.ReadValue(TagType type)
   at Substrate.Nbt.NbtTree.ReadTag(TagNodeCompound parent)
   at Substrate.Nbt.NbtTree.ReadCompound()
   at Substrate.Nbt.NbtTree.ReadValue(TagType type)
   at Substrate.Nbt.NbtTree.ReadTag(TagNodeCompound parent)
   at Substrate.Nbt.NbtTree.ReadCompound()
   at Substrate.Nbt.NbtTree.ReadValue(TagType type)
   at Substrate.Nbt.NbtTree.ReadRoot()
   at Substrate.Nbt.NbtTree.ReadFrom(Stream s)
   at NBTExplorer.Model.RegionChunkDataNode.ExpandCore()
   at NBTExplorer.Model.DataNode.Expand()
   at NBTExplorer.Controllers.NodeTreeController.ExpandNode(TreeNode node)
   at NBTExplorer.Windows.MainForm.ExpandNode(TreeNode node)
...

**Comment by kasamikona** [comment]
Update: was using an old version by mistake. Works fine in latest release.
